# Configuration Eclipse Mosquitto — SmartAgent-IoT
#
# allow_anonymous true : acceptable pour un projet local en développement.
# En production, on configurerait plutôt password_file + un fichier ACL par topic.
listener 1883
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_timestamp true
